<?php
// Nadpis
$_['heading_title'] = 'Licenčná zmluva';

// Text
$_['text_step_1']   = 'Prečítajte si prosím licenčnú zmluvu OpenCart';
$_['text_terms']    = '<h3>VŠEOBECNÁ VERZIA GNU</h3>
<p>Verzia 3, 29. jún 2007</p>
<p>Autorské práva &copy; 2007 Free Software Foundation, Inc. &lt;http://fsf.org/&gt;</p>
<p>Každý má oprávnenie kopírovať a distribuovať doslovné kópie tohto licenčného dokumentu, ale jeho zmena nie je povolená.</p>
<h3><a name="preamble"></a>Úvod</h3>
<p>GNU General Public License je slobodná, copyleft licencia pre softvér a iné druhy diel.</p>
<p>Licencie pre väčšinu softvéru a iných praktických diel sú navrhnuté tak, aby vás zbavili slobody zdieľať a meniť diela. Naopak, GNU General Public License má za cieľ zabezpečiť vašu slobodu zdieľať a meniť všetky verzie programu – aby ste mali istotu, že zostáva slobodným softvérom pre všetkých používateľov. My, Free Software Foundation, používame GNU General Public License pre väčšinu nášho softvéru; platí tiež pre akékoľvek iné dielo vydané týmto spôsobom jeho autorom. Môžete ju aplikovať aj na svoje programy.</p>
<p>Keď hovoríme o slobodnom softvéri, máme na mysli slobodu, nie cenu. Naše Všeobecné verejné licencie sú navrhnuté tak, aby ste mali istotu, že máte slobodu distribuovať kópie slobodného softvéru (a účtovať si za ne, ak si prajete), že dostanete zdrojový kód alebo ho môžete získať, ak ho chcete, že môžete softvér meniť alebo používať jeho časti v nových slobodných programoch, a že viete, že tieto veci môžete robiť.</p>
<p>Na ochranu vašich práv potrebujeme zabrániť iným, aby vám tieto práva upierali alebo vás žiadali, aby ste sa ich vzdali. Preto máte určité zodpovednosti, ak distribuujete kópie softvéru alebo ho upravujete: zodpovednosti rešpektovať slobodu iných.</p>
<p>Napríklad, ak distribuujete kópie takéhoto programu, či už zadarmo alebo za poplatok, musíte príjemcom poskytnúť rovnaké slobody, aké ste dostali vy. Musíte sa uistiť, že aj oni dostanú alebo môžu získať zdrojový kód. A musíte im ukázať tieto podmienky, aby poznali svoje práva.</p>
<p>Vývojári, ktorí používajú GNU GPL, chránia vaše práva dvoma krokmi: (1) uplatnia autorské práva na softvér a (2) ponúknu vám túto licenciu, ktorá vám dáva právne oprávnenie kopírovať, distribuovať a/alebo upravovať softvér.</p>
<p>Pre ochranu vývojárov a autorov GPL jasne vysvetľuje, že pre tento slobodný softvér neexistuje žiadna záruka. Pre dobro používateľov aj autorov GPL vyžaduje, aby boli upravené verzie označené ako zmenené, aby ich problémy neboli mylne pripisované autorom predchádzajúcich verzií.</p>
<p>Niektoré zariadenia sú navrhnuté tak, aby používateľom odopierali prístup k inštalácii alebo spusteniu upravených verzií softvéru v nich, hoci výrobca to môže urobiť. To je v zásadnom rozpore s cieľom chrániť slobodu používateľov meniť softvér. Systematický vzor takéhoto zneužívania sa vyskytuje v oblasti produktov pre jednotlivcov, čo je práve tam, kde je to najneprijateľnejšie. Preto sme navrhli túto verziu GPL tak, aby zakazovala túto prax pre tieto produkty. Ak sa takéto problémy výrazne vyskytnú v iných oblastiach, sme pripravení rozšíriť túto ustanovenie na tieto oblasti v budúcich verziách GPL, podľa potreby na ochranu slobody používateľov.</p>
<p>Nakoniec, každý program je neustále ohrozovaný softvérovými patentmi. Štáty by nemali umožňovať, aby patenty obmedzovali vývoj a používanie softvéru na všeobecných počítačoch, ale v tých, ktoré to robia, chceme zabrániť špeciálnemu nebezpečenstvu, že patenty aplikované na slobodný program by ho mohli efektívne privlastniť. Aby sme tomu zabránili, GPL zaisťuje, že patenty nemôžu byť použité na to, aby sa program stal neslobodným.</p>
<p>Presné podmienky a ustanovenia pre kopírovanie, distribúciu a úpravy nasledujú.</p>
<h3><a name="terms"></a>PODMIENKY A USTANOVENIA</h3>
<h4><a id="section0"></a>0. Definície.</h4>
<p>„Táto licencia“ sa vzťahuje na verziu 3 GNU General Public License.</p>
<p>„Autorské práva“ tiež znamenajú zákony podobné autorským právam, ktoré sa vzťahujú na iné druhy diel, ako sú polovodičové masky.</p>
<p>„Program“ sa vzťahuje na akékoľvek dielo chránené autorskými právami, ktoré je licencované pod touto licenciou. Každý nositeľ licencie je oslovovaný ako „vy“. „Nositelia licencie“ a „príjemcovia“ môžu byť jednotlivci alebo organizácie.</p>
<p>„Upraviť“ dielo znamená kopírovať z neho alebo prispôsobiť celé alebo časť diela spôsobom, ktorý vyžaduje povolenie autorských práv, okrem vytvorenia presnej kópie. Výsledné dielo sa nazýva „upravená verzia“ predchádzajúceho diela alebo dielo „založené na“ predchádzajúcom diele.</p>
<p>„Chránené dielo“ znamená buď neupravený Program alebo dielo založené na Programe.</p>
<p>„Šíriť“ dielo znamená robiť s ním čokoľvek, čo by bez povolenia viedlo k vašej priamej alebo sekundárnej zodpovednosti za porušenie autorských práv podľa platného autorského zákona, okrem vykonávania na počítači alebo úpravy súkromnej kópie. Šírenie zahŕňa kopírovanie, distribúciu (s úpravami alebo bez nich), sprístupnenie verejnosti a v niektorých krajinách aj iné činnosti.</p>
<p>„Prepraviť“ dielo znamená akýkoľvek druh šírenia, ktorý umožňuje iným stranám vyrobiť alebo prijať kópie. Samotná interakcia s používateľom prostredníctvom počítačovej siete, bez prenosu kópie, nie je preprava.</p>
<p>Interaktívne používateľské rozhranie zobrazuje „Vhodné právne oznámenia“ do tej miery, že obsahuje pohodlnú a viditeľnú funkciu, ktorá (1) zobrazuje vhodné oznámenie o autorských právach a (2) informuje používateľa, že pre dielo neexistuje žiadna záruka (okrem prípadov, keď sú poskytované záruky), že nositeľ licencie môže dielo prepravovať podľa tejto licencie a ako si môže pozrieť kópiu tejto licencie. Ak rozhranie zobrazuje zoznam používateľských príkazov alebo možností, ako je napríklad ponuka, prominentná položka v zozname spĺňa toto kritérium.</p>
<h4><a id="section1"></a>1. Zdrojový kód.</h4>
<p>„Zdrojový kód“ pre dielo znamená preferovanú formu diela na vykonávanie úprav. „Objektový kód“ znamená akúkoľvek formu diela, ktorá nie je zdrojovým kódom.</p>
<p>„Štandardné rozhranie“ znamená rozhranie, ktoré je buď oficiálnym štandardom definovaným uznávanou normalizačnou organizáciou, alebo v prípade rozhraní špecifikovaných pre konkrétny programovací jazyk, rozhranie, ktoré je široko používané medzi vývojármi pracujúcimi v tomto jazyku.</p>
<p>„Systémové knižnice“ vykonateľného diela zahŕňajú čokoľvek, okrem diela ako celku, čo (a) je zahrnuté v normálnej forme balenia hlavnej komponenty, ale nie je súčasťou tejto hlavnej komponenty, a (b) slúži len na umožnenie používania diela s touto hlavnou komponentou alebo na implementáciu štandardného rozhrania, pre ktoré je implementácia dostupná verejnosti vo forme zdrojového kódu. „Hlavná komponenta“ v tomto kontexte znamená hlavnú nevyhnutnú komponentu (jadro, okenný systém atď.) konkrétneho operačného systému (ak existuje), na ktorom vykonateľné dielo beží, alebo kompilátor použitý na vytvorenie diela, alebo interpret objektového kódu použitý na jeho spustenie.</p>
<p>„Zodpovedajúci zdrojový kód“ pre dielo vo forme objektového kódu znamená všetok zdrojový kód potrebný na generovanie, inštaláciu a (pre vykonateľné dielo) spustenie objektového kódu a na úpravu diela, vrátane skriptov na riadenie týchto činností. Nezahŕňa však systémové knižnice diela ani všeobecné nástroje alebo všeobecne dostupné slobodné programy, ktoré sú použité bez úprav pri vykonávaní týchto činností, ale nie sú súčasťou diela. Napríklad zodpovedajúci zdrojový kód zahŕňa súbory definícií rozhraní spojené so zdrojovými súbormi pre dielo a zdrojový kód pre zdieľané knižnice a dynamicky prepojené podprogramy, ktoré dielo špecificky vyžaduje, ako napríklad intímna dátová komunikácia alebo riadenie toku medzi týmito podprogrammi a inými časťami diela.</p>
<p>Zodpovedajúci zdrojový kód nemusí zahŕňať nič, čo môžu používatelia automaticky regenerovať z iných častí zodpovedajúceho zdrojového kódu.</p>
<p>Zodpovedajúci zdrojový kód pre dielo vo forme zdrojového kódu je to isté dielo.</p>
<h4><a id="section2"></a>2. Základné povolenia.</h4>
<p>Všetky práva udelené podľa tejto licencie sú udelené na dobu trvania autorských práv na Program a sú neodvolateľné za predpokladu, že sú splnené uvedené podmienky. Táto licencia výslovne potvrdzuje vaše neobmedzené povolenie na spustenie neupraveného Programu. Výstup zo spustenia chráneného diela je chránený touto licenciou iba vtedy, ak výstup, vzhľadom na jeho obsah, predstavuje chránené dielo. Táto licencia uznáva vaše práva na spravodlivé použitie alebo iné ekvivalentné práva, ako sú poskytované autorským zákonom.</p>
<p>Môžete vytvárať, spúšťať a šíriť chránené diela, ktoré neprepravujete, bez podmienok, pokiaľ vaša licencia inak zostáva v platnosti. Môžete prepravovať chránené diela iným výlučne za účelom, aby pre vás vykonali úpravy, alebo vám poskytli zariadenia na spustenie týchto diel, za predpokladu, že dodržiavate podmienky tejto licencie pri preprave všetkého materiálu, na ktorý nemáte autorské práva. Tí, ktorí pre vás vytvárajú alebo spúšťajú chránené diela, musia tak robiť výlučne vo vašom mene, pod vašim vedením a kontrolou, za podmienok, ktoré im zakazujú vytvárať akékoľvek kópie vášho materiálu chráneného autorskými právami mimo vášho vzťahu s vami.</p>
<p>Preprava za akýchkoľvek iných okolností je povolená výlučne za podmienok uvedených nižšie. Podlicencovanie nie je povolené; časť 10 to robí zbytočným.</p>
<h4><a id="section3"></a>3. Ochrana právnych práv používateľov pred zákonom proti obchádzaniu.</h4>
<p>Žiadne chránené dielo nebude považované za súčasť účinnej technologickej opatrenia podľa akéhokoľvek použiteľného zákona plniaceho záväzky podľa článku 11 Dohovoru o autorských právach WIPO prijatého 20. decembra 1996 alebo podobných zákonov zakazujúcich alebo obmedzujúcich obchádzanie takýchto opatrení.</p>
<p>Keď prepravujete chránené dielo, zriekate sa akéhokoľvek právneho oprávnenia zakázať obchádzanie technologických opatrení do tej miery, že takéto obchádzanie je vykonávané uplatňovaním práv podľa tejto licencie vo vzťahu k chránenému dielu, a vyhlasujete, že nemáte úmysel obmedziť prevádzku alebo úpravu diela ako prostriedku na presadzovanie vašich alebo tretích strán právnych práv zakázať obchádzanie technologických opatrení voči používateľom diela.</p>
<h4><a id="section4"></a>4. Preprava doslovných kópií.</h4>
<p>Môžete prepravovať doslovné kópie zdrojového kódu Programu tak, ako ste ho dostali, na akomkoľvek médiu, za predpokladu, že na každej kópii nápadne a primerane uverejníte vhodné oznámenie o autorských právach; ponecháte nedotknuté všetky oznámenia, že táto licencia a akékoľvek neprípustné podmienky pridané v súlade s časťou 7 sa vzťahujú na kód; ponecháte nedotknuté všetky oznámenia o neprítomnosti akýchkoľvek záruk; a poskytnete všetkým príjemcom kópiu tejto licencie spolu s Programom.</p>
<p>Môžete si účtovať akúkoľvek cenu alebo žiadnu cenu za každú kópiu, ktorú prepravujete, a môžete ponúknuť podporu alebo záručnú ochranu za poplatok.</p>
<h4><a id="section5"></a>5. Preprava upravených verzií zdrojového kódu.</h4>
<p>Môžete prepravovať dielo založené na Programe alebo úpravy na jeho vytvorenie z Programu vo forme zdrojového kódu za podmienok časti 4, za predpokladu, že splníte aj všetky tieto podmienky:</p>
<ul>
  <li>a) Dielo musí obsahovať nápadné oznámenia, že ste ho upravili, a uviesť relevantný dátum.</li>
  <li>b) Dielo musí obsahovať nápadné oznámenia, že je vydané podľa tejto licencie a akýchkoľvek podmienok pridaných podľa časti 7. Táto požiadavka upravuje požiadavku v časti 4 „ponechať nedotknuté všetky oznámenia“.</li>
  <li>c) Musíte poskytnúť licenciu na celé dielo ako celok podľa tejto licencie komukoľvek, kto príde do vlastníctva kópie. Táto licencia sa preto bude vzťahovať spolu s akýmikoľvek použiteľnými dodatočnými podmienkami časti 7 na celé dielo a všetky jeho časti, bez ohľadu na to, ako sú zabalené. Táto licencia neudeluje povolenie na poskytnutie licencie na dielo akýmkoľvek iným spôsobom, ale nezneplatňuje také povolenie, ak ste ho samostatne dostali.</li>
  <li>d) Ak má dielo interaktívne používateľské rozhrania, každé musí zobrazovať vhodné právne oznámenia; avšak, ak má Program interaktívne rozhrania, ktoré nezobrazujú vhodné právne oznámenia, vaše dielo ich nemusí zobrazovať.</li>
</ul>
<p>Kompilácia chráneného diela s inými samostatnými a nezávislými dielami, ktoré nie sú svojou povahou rozšíreniami chráneného diela a ktoré nie sú s ním kombinované tak, aby tvorili väčší program, na alebo v zväzku úložného alebo distribučného média, sa nazýva „agregát“, ak kompilácia a jej výsledné autorské práva nie sú použité na obmedzenie prístupu alebo právnych práv používateľov kompilácie nad rámec toho, čo umožňujú jednotlivé diela. Zahrnutie chráneného diela do agregátu nespôsobuje, že sa táto licencia vzťahuje na ostatné časti agregátu.</p>
<h4><a id="section6"></a>6. Preprava nezdrojových foriem.</h4>
<p>Môžete prepravovať chránené dielo vo forme objektového kódu za podmienok častí 4 a 5, za predpokladu, že tiež prepravíte strojovo čitateľný zodpovedajúci zdrojový kód podľa podmienok tejto licencie jedným z týchto spôsobov:</p>
<ul>
  <li>a) Prepravte objektový kód v alebo vstavaný do fyzického produktu (vrátane fyzického distribučného média), sprevádzaný zodpovedajúcim zdrojovým kódom uloženým na odolnom fyzickom médiu zvyčajne používanom na výmenu softvéru.</li>
  <li>b) Prepravte objektový kód v alebo vstavaný do fyzického produktu (vrátane fyzického distribučného média), sprevádzaný písomnou ponukou, platnou najmenej tri roky a platnou tak dlho, ako ponúkate náhradné diely alebo zákaznícku podporu pre tento model produktu, poskytnúť komukoľvek, kto vlastní objektový kód, buď (1) kópiu zodpovedajúceho zdrojového kódu pre všetok softvér v produkte, ktorý je chránený touto licenciou, na odolnom fyzickom médiu zvyčajne používanom na výmenu softvéru, za cenu nie vyššiu, ako sú vaše primerané náklady na fyzické vykonanie tejto prepravy zdrojového kódu, alebo (2) prístup na kopírovanie zodpovedajúceho zdrojového kódu zo sieťového servera bez poplatku.</li>
  <li>c) Prepravte jednotlivé kópie objektového kódu s kópiou písomnej ponuky na poskytnutie zodpovedajúceho zdrojového kódu. Táto alternatíva je povolená iba občasne a nekomerčne a iba vtedy, ak ste dostali objektový kód s takouto ponukou v súlade s pododdielom 6b.</li>
  <li>d) Prepravte objektový kód ponúknutím prístupu z určeného miesta (bezplatne alebo za poplatok) a ponúknite ekvivalentný prístup k zodpovedajúcemu zdrojovému kódu rovnakým spôsobom cez to isté miesto bez ďalšieho poplatku. Nemusíte vyžadovať, aby príjemcovia kopírovali zodpovedajúci zdrojový kód spolu s objektovým kódom. Ak je miestom na kopírovanie objektového kódu sieťový server, zodpovedajúci zdrojový kód môže byť na inom serveri (prevádzkovanom vami alebo treťou stranou), ktorý podporuje ekvivalentné kopírovacie zariadenia, za predpokladu, že udržiavate jasné pokyny vedľa objektového kódu, ktoré uvádzajú, kde nájsť zodpovedajúci zdrojový kód. Bez ohľadu na to, ktorý server hostí zodpovedajúci zdrojový kód, zostávate povinní zabezpečiť, aby bol dostupný tak dlho, ako je potrebné na splnenie týchto požiadaviek.</li>
  <li>e) Prepravte objektový kód pomocou peer-to-peer prenosu, za predpokladu, že informujete ostatných peerov, kde sa objektový kód a zodpovedajúci zdrojový kód diela ponúka verejnosti bez poplatku podľa pododdielu 6d.</li>
</ul>
<p>Oddeliteľná časť objektového kódu, ktorej zdrojový kód je vylúčený zo zodpovedajúceho zdrojového kódu ako systémová knižnica, nemusí byť zahrnutá pri preprave objektového kódu diela.</p>
<p>„Používateľský produkt“ je buď (1) „spotrebný produkt“, čo znamená akýkoľvek hmotný osobný majetok, ktorý sa zvyčajne používa na osobné, rodinné alebo domáce účely, alebo (2) čokoľvek navrhnuté alebo predávané na začlenenie do obydlia. Pri určovaní, či je produkt spotrebným produktom, sa pochybné prípady riešia v prospech pokrytia. Pre konkrétny produkt prijatý konkrétnym používateľom sa „zvyčajne používa“ vzťahuje na typické alebo bežné použitie tejto triedy produktu, bez ohľadu na stav konkrétneho používateľa alebo na spôsob, akým konkrétny používateľ produkt skutočne používa alebo očakáva, že ho bude používať. Produkt je spotrebným produktom bez ohľadu na to, či má významné komerčné, priemyselné alebo nekomerčné použitie, pokiaľ takéto použitie nepredstavuje jediný významný spôsob použitia produktu.</p>
<p>„Inštalačné informácie“ pre používateľský produkt znamenajú akékoľvek metódy, postupy, autorizačné kľúče alebo iné informácie potrebné na inštaláciu a spustenie upravených verzií chráneného diela v tomto používateľskom produkte z upravenej verzie jeho zodpovedajúceho zdrojového kódu. Informácie musia stačiť na zabezpečenie, aby pokračujúce fungovanie upraveného objektového kódu nebolo v žiadnom prípade zabránené alebo narušené výlučne z dôvodu, že bola vykonaná úprava.</p>
<p>Ak prepravujete objektový kód diela podľa tejto časti v, s alebo špecificky na použitie v používateľskom produkte a preprava sa uskutočňuje ako súčasť transakcie, v ktorej sa právo vlastníctva a používania používateľského produktu prenáša na príjemcu navždy alebo na stanovené obdobie (bez ohľadu na to, ako je transakcia charakterizovaná), zodpovedajúci zdrojový kód prepravený podľa tejto časti musí byť sprevádzaný inštalačnými informáciami. Táto požiadavka sa však nevzťahuje, ak ani vy, ani žiadna tretia strana nezachováva schopnosť inštalovať upravený objektový kód do používateľského produktu (napríklad dielo bolo nainštalované do ROM).</p>
<p>Požiadavka na poskytnutie inštalačných informácií nezahŕňa požiadavku na pokračovanie v poskytovaní podporných služieb, záruky alebo aktualizácií pre dielo, ktoré bolo upravené alebo nainštalované príjemcom, alebo pre používateľský produkt, v ktorom bolo upravené alebo nainštalované. Prístup k sieti môže byť odopretý, ak úprava sama o sebe podstatne a nepriaznivo ovplyvňuje prevádzku siete alebo porušuje pravidlá a protokoly pre komunikáciu cez sieť.</p>
<p>Zodpovedajúci zdrojový kód prepravený a inštalačné informácie poskytnuté v súlade s touto časťou musia byť vo formáte, ktorý je verejne dokumentovaný (a s implementáciou dostupnou verejnosti vo forme zdrojového kódu), a nesmú vyžadovať žiadne špeciálne heslo alebo kľúč na rozbalenie, čítanie alebo kopírovanie.</p>
<h4><a id="section7"></a>7. Dodatočné podmienky.</h4>
<p>„Dodatočné povolenia“ sú podmienky, ktoré dopĺňajú podmienky tejto licencie tým, že robia výnimky z jednej alebo viacerých jej podmienok. Dodatočné povolenia, ktoré sa vzťahujú na celý Program, sa považujú za súčasť tejto licencie do tej miery, že sú platné podľa použiteľného zákona. Ak sa dodatočné povolenia vzťahujú iba na časť Programu, táto časť môže byť použitá samostatne podľa týchto povolení, ale celý Program zostáva riadený touto licenciou bez ohľadu na dodatočné povolenia.</p>
<p>Keď prepravujete kópiu chráneného diela, môžete podľa vlastného uváženia odstrániť akékoľvek dodatočné povolenia z tejto kópie alebo z akejkoľvek jej časti. (Dodatočné povolenia môžu byť napísané tak, aby vyžadovali ich vlastné odstránenie v určitých prípadoch, keď dielo upravíte.) Môžete umiestniť dodatočné povolenia na materiál, ktorý ste pridali k chránenému dielu, pre ktorý máte alebo môžete poskytnúť príslušné povolenie autorských práv.</p>
<p>Bez ohľadu na akékoľvek iné ustanovenie tejto licencie, pre materiál, ktorý pridáte k chránenému dielu, môžete (ak ste oprávnení držiteľmi autorských práv tohto materiálu) doplniť podmienky tejto licencie o podmienky:</p>
<ul>
  <li>a) Vylúčenie záruky alebo obmedzenie zodpovednosti odlišne od podmienok častí 15 a 16 tejto licencie; alebo</li>
  <li>b) Požadovanie zachovania určitých rozumných právnych oznámení alebo atribúcií autorov v tomto materiáli alebo vo vhodných právnych oznámeniach zobrazovaných dielami, ktoré ho obsahujú; alebo</li>
  <li>c) Zákaz nesprávneho uvádzania pôvodu tohto materiálu alebo požadovanie, aby boli upravené verzie takéhoto materiálu označené rozumným spôsobom ako odlišné od pôvodnej verzie; alebo</li>
  <li>d) Obmedzenie použitia na propagačné účely mien poskytovateľov licencií alebo autorov materiálu; alebo</li>
  <li>e) Odmietnutie udelenia práv podľa zákona o ochranných známkach na použitie niektorých obchodných mien, ochranných známok alebo služobných značiek; alebo</li>
  <li>f) Požadovanie odškodnenia poskytovateľov licencií a autorov tohto materiálu kýmkoľvek, kto prepravuje materiál (alebo upravené verzie) so zmluvnými predpokladmi zodpovednosti voči príjemcovi za akúkoľvek zodpovednosť, ktorú tieto zmluvné predpoklady priamo ukladajú týmto poskytovateľom licencií a autorom.</li>
</ul>
<p>Všetky ostatné neprípustné dodatočné podmienky sa považujú za „ďalšie obmedzenia“ v zmysle časti 10. Ak Program, ktorý ste dostali, alebo akákoľvek jeho časť obsahuje oznámenie, že je riadený touto licenciou spolu s podmienkou, ktorá je ďalším obmedzením, môžete túto podmienku odstrániť. Ak licenčný dokument obsahuje ďalšie obmedzenie, ale umožňuje prelicencovanie alebo prepravu podľa tejto licencie, môžete pridať k chránenému dielu materiál riadený podmienkami tohto licenčného dokumentu, za predpokladu, že ďalšie obmedzenie takéto prelicencovanie alebo prepravu neprežije.</p>
<p>Ak pridáte podmienky k chránenému dielu v súlade s touto časťou, musíte umiestniť v príslušných zdrojových súboroch vyhlásenie o dodatočných podmienkach, ktoré sa na ne vzťahujú, alebo oznámenie, ktoré uvádza, kde nájsť použiteľné podmienky.</p>
<p>Dodatočné podmienky, prípustné alebo neprípustné, môžu byť uvedené vo forme samostatne napísanej licencie alebo uvedené ako výnimky; vyššie uvedené požiadavky platia v oboch prípadoch.</p>
<h4><a id="section8"></a>8. Ukončenie.</h4>
<p>Nesmiete šíriť ani upravovať chránené dielo, okrem výslovne uvedeného v tejto licencii. Akýkoľvek pokus o šírenie alebo úpravu inak je neplatný a automaticky ukončí vaše práva podľa tejto licencie (vrátane akýchkoľvek patentových licencií udelených podľa tretieho odseku časti 11).</p>
<p>Avšak, ak prestanete porušovať túto licenciu, vaša licencia od konkrétneho držiteľa autorských práv je obnovená (a) dočasne, pokiaľ a kým držiteľ autorských práv výslovne a konečne neukončí vašu licenciu, a (b) trvalo, ak držiteľ autorských práv vás neupozorní na porušenie nejakým rozumným spôsobom do 60 dní po ukončení porušovania.</p>
<p>Navyše, vaša licencia od konkrétneho držiteľa autorských práv je trvalo obnovená, ak vás držiteľ autorských práv upozorní na porušenie nejakým rozumným spôsobom, toto je prvýkrát, čo ste dostali oznámenie o porušení tejto licencie (pre akékoľvek dielo) od tohto držiteľa autorských práv, a vy porušenie napravíte do 30 dní od prijatia oznámenia.</p>
<p>Ukončenie vašich práv podľa tejto časti neukončuje licencie strán, ktoré dostali kópie alebo práva od vás podľa tejto licencie. Ak boli vaše práva ukončené a nie sú trvalo obnovené, nemáte nárok na prijatie nových licencií pre rovnaký materiál podľa časti 10.</p>
<h4><a id="section9"></a>9. Prijatie nie je potrebné na získanie kópií.</h4>
<p>Nie ste povinní prijať túto licenciu, aby ste dostali alebo spustili kópiu Programu. Vedľajšie šírenie chráneného diela, ktoré sa vyskytuje výlučne ako dôsledok použitia peer-to-peer prenosu na prijatie kópie, tiež nevyžaduje prijatie. Avšak, nič iné ako táto licencia vám neudeluje povolenie šíriť alebo upravovať akékoľvek chránené dielo. Tieto činnosti porušujú autorské práva, ak túto licenciu neprijmete. Preto úpravou alebo šírením chráneného diela vyjadrujete svoje prijatie tejto licencie na vykonanie týchto činností.</p>
<h4><a id="section10"></a>10. Automatické licencovanie následných príjemcov.</h4>
<p>Zakaždým, keď prepravujete chránené dielo, príjemca automaticky dostáva licenciu od pôvodných poskytovateľov licencií na spustenie, úpravu a šírenie tohto diela podľa tejto licencie. Nie ste zodpovední za presadzovanie dodržiavania tejto licencie tretími stranami.</p>
<p>„Transakcia subjektu“ je transakcia, ktorá prenáša kontrolu nad organizáciou alebo podstatne všetky aktíva jednej organizácie, alebo rozdeľuje organizáciu, alebo spája organizácie. Ak šírenie chráneného diela vyplýva z transakcie subjektu, každá strana tejto transakcie, ktorá dostane kópiu diela, tiež dostane akékoľvek licencie na dielo, ktoré mal predchodca strany v záujme alebo mohol poskytnúť podľa predchádzajúceho odseku, plus právo na vlastníctvo zodpovedajúceho zdrojového kódu diela od predchodcu v záujme, ak ho predchodca má alebo ho môže získať s rozumným úsilím.</p>
<p>Nesmiete ukladať žiadne ďalšie obmedzenia na výkon práv udelených alebo potvrdených touto licenciou. Napríklad, nesmiete ukladať licenčný poplatok, licenčnú odplatu alebo iný poplatok za výkon práv udelených podľa tejto licencie, a nesmiete iniciovať žalobu (vrátane krížovej žaloby alebo protinároku v súdnom spore) tvrdiac, že akýkoľvek patentový nárok je porušený výrobou, používaním, predajom, ponúkaním na predaj alebo dovozom Programu alebo akejkoľvek jeho časti.</p>
<h4><a id="section11"></a>11. Patenty.</h4>
<p>„Prispievateľ“ je držiteľ autorských práv, ktorý autorizuje použitie podľa tejto licencie Programu alebo diela, na ktorom je Program založený. Dielo takto licencované sa nazýva „verzia prispievateľa“ prispievateľa.</p>
<p>„Základné patentové nároky“ prispievateľa sú všetky patentové nároky vlastnené alebo kontrolované prispievateľom, už získané alebo získané neskôr, ktoré by boli porušené nejakým spôsobom povoleným touto licenciou pri výrobe, používaní alebo predaji jeho verzie prispievateľa, ale nezahŕňajú nároky, ktoré by boli porušené iba ako dôsledok ďalšej úpravy verzie prispievateľa. Pre účely tejto definície „kontrola“ zahŕňa právo poskytnúť patentové podlicencie v súlade s požiadavkami tejto licencie.</p>
<p>Každý prispievateľ vám udeluje nevýhradnú, celosvetovú, bezplatnú patentovú licenciu podľa základných patentových nárokov prispievateľa na výrobu, používanie, predaj, ponúkanie na predaj, dovoz a inak spustenie, úpravu a šírenie obsahu jeho verzie prispievateľa.</p>
<p>V nasledujúcich troch odsekoch „patentová licencia“ znamená akúkoľvek expresnú dohodu alebo záväzok, akokoľvek označený, nepresadzovať patent (ako napríklad expresné povolenie na uplatňovanie patentu alebo zmluvu nepodávať žalobu na porušenie patentu). „Udelenie“ takejto patentovej licencie strane znamená uzavretie takejto dohody alebo záväzku nepresadzovať patent voči strane.</p>
<p>Ak prepravujete chránené dielo, vedome sa spoliehajúc na patentovú licenciu, a zodpovedajúci zdrojový kód diela nie je k dispozícii nikomu na kopírovanie, bezplatne a podľa podmienok tejto licencie, cez verejne dostupný sieťový server alebo iné ľahko dostupné prostriedky, potom musíte buď (1) zabezpečiť, aby bol zodpovedajúci zdrojový kód takto dostupný, alebo (2) zabezpečiť, aby ste sa sami zbavili výhody patentovej licencie pre toto konkrétne dielo, alebo (3) zabezpečiť, v súlade s požiadavkami tejto licencie, rozšírenie patentovej licencie na následných príjemcov. „Vedome sa spoliehajúc“ znamená, že máte skutočné vedomosti, že bez patentovej licencie by vaša preprava chráneného diela v krajine alebo použitie chráneného diela vaším príjemcom v krajine porušilo jeden alebo viac identifikovateľných patentov v tejto krajine, o ktorých máte dôvod domnievať sa, že sú platné.</p>
<p>Ak v súvislosti s jednou transakciou alebo dohodou prepravujete alebo šírite zabezpečením prepravy chráneného diela a udelíte patentovú licenciu niektorým stranám prijímajúcim chránené dielo, ktorá im umožňuje používať, šíriť, upravovať alebo prepravovať konkrétnu kópiu chráneného diela, potom patentová licencia, ktorú udelíte, je automaticky rozšírená na všetkých príjemcov chráneného diela a diel založených na ňom.</p>
<p>Patentová licencia je „diskriminačná“, ak nezahŕňa do svojho rozsahu, zakazuje výkon alebo je podmienená nevýkonom jedného alebo viacerých práv, ktoré sú špecificky udelené podľa tejto licencie. Nesmiete prepravovať chránené dielo, ak ste stranou dohody s treťou stranou, ktorá sa zaoberá distribúciou softvéru, podľa ktorej platíte tretej strane na základe rozsahu vašej činnosti prepravy diela, a podľa ktorej tretá strana udelí akejkoľvek strane, ktorá by od vás dostala chránené dielo, diskriminačnú patentovú licenciu (a) v súvislosti s kópiami chráneného diela prepravenými vami (alebo kópiami vyrobenými z týchto kópií), alebo (b) primárne pre a v súvislosti so špecifickými produktmi alebo kompiláciami, ktoré obsahujú chránené dielo, pokiaľ ste do tejto dohody nevstúpili alebo patentová licencia nebola udelená pred 28. marcom 2007.</p>
<p>Nič v tejto licencii sa nesmie vykladať ako vylučujúce alebo obmedzujúce akékoľvek implicitné licencie alebo iné obhajoby proti porušeniu, ktoré môžu byť inak dostupné podľa platného patentového zákona.</p>
<h4><a id="section12"></a>12. Nevzdanie sa slobody iných.</h4>
<p>Ak sú na vás uložené podmienky (či už súdnym príkazom, dohodou alebo inak), ktoré sú v rozpore s podmienkami tejto licencie, neoslobodzujú vás od podmienok tejto licencie. Ak nemôžete prepravovať chránené dielo tak, aby ste súčasne splnili svoje povinnosti podľa tejto licencie a akékoľvek iné relevantné povinnosti, potom v dôsledku toho nemôžete dielo prepravovať vôbec. Napríklad, ak súhlasíte s podmienkami, ktoré vás zaväzujú vyberať licenčný poplatok za ďalšiu prepravu od tých, ktorým prepravujete Program, jediným spôsobom, ako by ste mohli splniť obe tieto podmienky a túto licenciu, by bolo úplne sa zdržať prepravy Programu.</p>
<h4><a id="section13"></a>13. Použitie s GNU Affero General Public License.</h4>
<p>Bez ohľadu na akékoľvek iné ustanovenie tejto licencie máte povolenie prepojiť alebo kombinovať akékoľvek chránené dielo s dielom licencovaným podľa verzie 3 GNU Affero General Public License do jedného kombinovaného diela a prepravovať výsledné dielo. Podmienky tejto licencie sa budú naďalej vzťahovať na časť, ktorou je chránené dielo, ale špeciálne požiadavky GNU Affero General Public License, časť 13, týkajúce sa interakcie cez sieť, sa budú vzťahovať na kombináciu ako takú.</p>
<h4><a id="section14"></a>14. Revidované verzie tejto licencie.</h4>
<p>Free Software Foundation môže publikovať revidované a/alebo nové verzie GNU General Public License z času na čas. Takéto nové verzie budú podobné duchu tejto verzie, ale môžu sa líšiť v detailoch, aby riešili nové problémy alebo obavy.</p>
<p>Každá verzia má pridelené rozlišovacie číslo verzie. Ak Program špecifikuje, že naň platí určité číslovaná verzia GNU General Public License „alebo akákoľvek neskoršia verzia“, máte možnosť dodržiavať podmienky a ustanovenia buď tejto číslovanej verzie alebo akejkoľvek neskoršej verzie publikovanej Free Software Foundation. Ak Program nešpecifikuje číslo verzie GNU General Public License, môžete si vybrať akúkoľvek verziu, ktorá bola kedykoľvek publikovaná Free Software Foundation.</p>
<p>Ak Program špecifikuje, že proxy môže rozhodnúť, ktoré budúce verzie GNU General Public License môžu byť použité, verejné vyhlásenie proxy o prijatí verzie vás trvalo oprávňuje vybrať túto verziu pre Program.</p>
<p>Neskoršie verzie licencií vám môžu poskytnúť dodatočné alebo odlišné povolenia. Avšak, na žiadneho autora alebo držiteľa autorských práv nie sú ukladané žiadne dodatočné povinnosti v dôsledku vášho rozhodnutia dodržiavať neskoršiu verziu.</p>
<h4><a id="section15"></a>15. Vylúčenie záruky.</h4>
<p>POKIAĽ TO UMOŽŇUJE PRÍSLUŠNÝ ZÁKON, PROGRAM JE POSKYTOVANÝ BEZ AKEJKOĽVEK ZÁRUKY. POKIAĽ NIE JE STANOVENÉ INÁK PÍSOMNE, DRŽITELIA AUTORSKÝCH PRÁV A/ALEBO INÉ STRANY POSKYTUJÚ PROGRAM „TAK, AKO JE“ BEZ ZÁRUKY AKEJKOĽVEK DRUHU, ČI UŽ VYJADRENEJ ALEBO IMPLIKOVANEJ, VRÁTANE, ALE NIE JE OBMEDZENÉ NA, IMPLIKOVANÉ ZÁRUKY OBCHODOVATEĽNOSTI A VHODNOSTI NA KONKRÉTNY ÚČEL. CELÉ RIZIKO POKIAĽ SA TÝKA KVALITY A VÝKONU PROGRAMU JE NA VÁS. AK BY PROGRAM BOL CHYBNÝ, PREDPOKLÁDAJTE NÁKLADY NA VŠETKY POTREBNÉ SERVISNÉ, OPRAVNÉ ALEBO OPRAVUJÚCE PRÁCE.</p>
<h4><a id="section16"></a>16. Obmedzenie zodpovednosti.</h4>
<p>V ŽIADNOM PRÍPADE, POKIAĽ TO NIE JE VYŽADOVANÉ PRÍSLUŠNÝM ZÁKONOM ALEBO DOHODNUTÉ PÍSOMNE, NEBUDE ŽIADNY DRŽITEĽ AUTORSKÝCH PRÁV, ALEBO ŽIADNA INÁ STRANA, KTORÁ UPRAVUJE A/ALEBO PREPRAVUJE PROGRAM PODĽA PREDCHOZIEHO POVOLENIA, ZODPOVEDNÁ VÁM ZA ŠKODY, VRÁTANE AKÝCHKOĽVEK VŠEOBECNÝCH, ŠPECIÁLNYCH, NÁHODNÝCH ALEBO NÁSLEDNÝCH ŠKÔD VYPLÝVAJÚCICH Z POUŽITIA ALEBO NEMOŽNOSTI POUŽITIA PROGRAMU (VRÁTANE, ALE NIE JE OBMEDZENÉ NA, STRATY ÚDAJOV ALEBO ÚDAJE POSKYTOVANÉ NESPRÁVNE ALEBO STRATY ZAZNANÉ VAMI ALEBO TRETÍMI STRANAMI ALEBO ZLYHANIE PROGRAMU SPOLUPRACOVAŤ S INÝMI PROGRAMAMI), AJ KEĎ BOL TAKÝ DRŽITEĽ ALEBO INÁ STRANA UPOMENUTÁ NA MOŽNOSŤ TAKÝCH ŠKÔD.</p>
<h4><a id="section17"></a>17. Výklad častí 15 a 16.</h4>
<p>Ak vylúčenie záruky a obmedzenie zodpovednosti uvedené vyššie nemôže byť poskytnuté podľa svojich podmienok miestnym zákonom, preverujúce súdy použijú miestny zákon, ktorý najviac približuje absolútnemu zrieknutiu sa všetkých občianskych zodpovedností v súvislosti s Programom, pokiaľ záruka alebo predpoklad zodpovednosti nesprevádza kópiu Programu výmenou za poplatok.</p>
<p>KONIEC PODMIENOK A USTANOVENÍ</p>
<h3><a name="howto"></a>Ako aplikovať tieto podmienky na vaše nové programy</h3>
<p>Ak vyvíjate nový program a chcete, aby bol čo najužitočnejší pre verejnosť, najlepším spôsobom, ako to dosiahnuť, je urobiť ho slobodným softvérom, ktorý môže každý redistribuovať a meniť podľa týchto podmienok.</p>
<p>Ak to chcete urobiť, pripojte k programu nasledujúce oznámenia. Najbezpečnejšie je pripojiť ich na začiatok každého zdrojového súboru, aby najúčinnejšie vylúčili záruku; a každý súbor by mal mať aspoň riadok „autorské práva“ a odkaz na miesto, kde sa nachádza úplné oznámenie.</p>
<pre>&lt;jeden riadok na uvedenie názvu programu a stručnú predstavu o tom, čo robí.&gt; Autorské práva (C) &lt;rok&gt; &lt;meno autora&gt;

Tento program je slobodný softvér: môžete ho redistribuovať a/alebo upravovať podľa podmienok GNU General Public License, ako ju publikuje Free Software Foundation, buď verzie 3 tejto licencie, alebo (podľa vášho uváženia) akejkoľvek neskoršej verzie.

Tento program je distribuovaný v nádeji, že bude užitočný, ale BEZ AKÝCHKOĽVEK ZÁRUK; dokonca bez implicitnej záruky OBCHODOVATEĽNOSTI alebo VHODNOSTI NA KONKRÉTNY ÚČEL. Viac podrobností nájdete v GNU General Public License.

Kópiu GNU General Public License by ste mali dostať spolu s týmto programom. Ak nie, pozrite si &lt;http://www.gnu.org/licenses/&gt;.</pre>
<p>Tiež pridajte informácie o tom, ako vás kontaktovať elektronickou poštou a poštou.</p>
<p>Ak program vykonáva interakciu s terminálom, uistite sa, že pri spustení v interaktívnom režime vypíše krátke oznámenie podobné tomuto:</p>
<pre>&lt;program&gt; Autorské práva (C) &lt;rok&gt; &lt;meno autora&gt; Tento program prichádza s ABSOLÚTNE ŽIADNOU ZÁRUKOU; pre podrobnosti zadajte `show w\'. Toto je slobodný softvér a ste vítaní ho redistribuovať za určitých podmienok; zadajte `show c\' pre podrobnosti. </pre>
<p>Hypotetické príkazy `show w\' a `show c\' by mali zobraziť príslušné časti GNU General Public License. Samozrejme, príkazy vášho programu môžu byť odlišné; pre grafické používateľské rozhranie by ste použili „informačné okno“.</p>
<p>Mali by ste tiež požiadať svojho zamestnávateľa (ak pracujete ako programátor) alebo školu, ak existuje, aby podpísali „vylúčenie zodpovednosti za autorské práva“ pre program, ak je to potrebné. Pre viac informácií o tom a o tom, ako aplikovať a dodržiavať GNU GPL, pozrite si &lt;http://www.gnu.org/licenses/&gt;.</p>
<p>GNU General Public License neumožňuje začlenenie vášho programu do vlastníckeho softvéru. Ak je váš program knižnica podprogramov, môžete zvážiť užitočnejšie povoliť prepojenie vlastníckych aplikácií s knižnicou. Ak to chcete urobiť, použite namiesto tejto licencie GNU Lesser General Public License. Najprv si však prečítajte &lt;http://www.gnu.org/philosophy/why-not-lgpl.html&gt;.</p>';
